### PR TITLE
Add JSDoc types and build a typescript declaration

### PR DESCRIPTION
**Pull request by lukaw3d**
Mitigates https://github.com/oasislabs/deoxysii.js/issues/12

### CODE REVIEW

**Review by nhynes — APPROVED** [review]
🙇

**Comment by xmzheng** [comment]
👍

**Review by kostko — APPROVED** [review]

**Comment by kostko** [comment]
Fixed some of the repo config so this should be mergable now.

**Comment by kostko** [comment]
Also it may be nice to update the broken badge in the README (which points to CircleCI).

**Pull request merged**
